### ISSUE TITLE
Oneway

### ISSUE THREAD

**Issue by dpalecek** [barrettc/swa-price-drop#1]
I book a lot of my swa flight via one-way fares. Anyway to change it to just search a one-way fare and alert you?

**Comment by barrettc** [comment]
That shouldn't be too difficult. I'm traveling this week for Thanksgiving but can take a look next week

**Comment by barrettc** [comment]
Had some downtime and fixed this. I'll update the README later but the yaml format for a one way trip is:

```yaml
flights:
  - outboundFlightNumber: 4288
    originAirport: AUS
    destinationAirport: MSY
    outboundDate: 2/17/2017
    adultPassengerCount: 1
    outboundPrice: 255
```

You can also have a mix of round trip and one way trips:

```yaml
flights:
  - outboundFlightNumber: 4288
    originAirport: AUS
    destinationAirport: MSY
    outboundDate: 2/17/2017
    adultPassengerCount: 1
    outboundPrice: 255
  - outboundFlightNumber: 5030
    returnFlightNumber: 6592
    originAirport: AUS
    destinationAirport: MCO
    outboundDate: 3/11/2017
    returnDate: 3/18/2017
    adultPassengerCount: 1
    outboundPrice: 219
    returnPrice: 241
```
