### ISSUE TITLE
HTML being returned for international flights is different

### ISSUE THREAD

**Issue by barrettc** [barrettc/swa-price-drop#3]
Received an email with the following parameters:

```yaml
flights:
  # round trip
  - outboundFlightNumber: 514
    returnFlightNumber: 515
    originAirport: DEN
    destinationAirport: PVR
    outboundDate: 07/18/2017
    returnDate: 07/28/2017
    adultPassengerCount: 1
    outboundPrice: 276
    returnPrice: 324
```

yields:

2017-03-31T22:44:03.112Z - info: Checking southwest.com for prices with parameters:
originAirport: DEN
destinationAirport: PVR
outboundDateString: 07/18/2017
returnDateString: 07/28/2017
adultPassengerCount: 1
2017-03-31T22:44:05.495Z - debug: Lowest outbound price for flight number 514 is Infinity
2017-03-31T22:44:05.496Z - debug: Notification threshold outbound price for flight 514 is 276
2017-03-31T22:44:05.496Z - debug: Lowest return price for flight number 6515 is Infinity
2017-03-31T22:44:05.497Z - debug: Notification threshold return price for flight 6515 is 324

The problem is that the HTML being returned for international flights (Puerto Vallarta) is completely different and so the scraper logic is broken.
